// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjelhichfibzkopunhpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqZWxoaWNoZmliemtvcHVuaHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODE4NDAsImV4cCI6MjA2NDQ1Nzg0MH0.0QJiGPY6kA_Nd0lmdPgufPTLFQRPY0hPLlKfrs1dsIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);